# Core Attrs
title: "Trevor Marburger"
author: "Trevor Marburger"
permalink: /:title/
lang: "en"
show_excerpts: true
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
minimal: false
mathjax: true

# Links
navigation:
  - {title: Posts, icon: book, url: "/posts.html"}
  - {title: Mail, icon: envelope, url: "mailto:trevormarburger@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/trevormarburger/"}
  - {title: LinkedIn, icon: linkedin-in, url: "https://linkedin.com/in/trevormarburger"}
  - {title: Feed, icon: rss, url: "/feed.xml"}

remote_theme: niklasbuschmann/contrast

plugins:
 - jekyll-feed
